<a href="https://colab.research.google.com/github/Lotfullah21/PyLibraries/blob/main/F22_Recitation0b_Fundamentals_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recitation0b-NumPy
## Contents
1. Installation
2. Initialization
3. Accessing and modifying data
4. Pivoting data
5. Combining data
6. Math operations

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides and an assortment of operations for fast operations on arrays - from mathematical, logical operations to basic linear algebra, random simulation and much more.

# 1. Installation
Generally NumPy is pre-installed on CoLab/AWS. You should first check if NumPy is available and its version.

To manually install Numpy, please follow the instructions below.

In [2]:
# Check the installation of NumPy
!pip show numpy

# Install NumPy
# !pip install numpy

Name: numpy
Version: 1.21.6
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, xarray-einstats, wordcloud, torchvision, torchtext, tifffile, thinc, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, scikit-image, resampy, qudida, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc, pyerfa, pyemd, pycocotools, pyarrow, prophet, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-python-headless, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, https

In [3]:
# Import the NumPy 
import numpy as np

# 2. Initialization


Initialize new NumPy arrays

## a. Create an empty array/ zeros array/ ones array

In [4]:
# initialize an empty array with size 2 x 2
empty_arr = np.empty((2, 2))
print("An empty array is \n", empty_arr, " with dimensions ", empty_arr.shape, "\n")

An empty array is 
 [[5.e-324 5.e-324]
 [5.e-324 0.e+000]]  with dimensions  (2, 2) 



In [5]:
empty_array = np.empty((2,2))
print(empty_array)

[[5.e-324 5.e-324]
 [5.e-324 0.e+000]]


In [6]:
zero_array = np.zeros((4,4,2))
print(zero_array)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [7]:
# initialize an all zero array with size 2 x 3
zeros_arr = np.zeros((2, 3))
print("A zeros array is \n", zeros_arr, " with dimensions ", zeros_arr.shape, "\n")

A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]]  with dimensions  (2, 3) 



In [8]:
# initialize an all one array with size 4 x 2
ones_arr = np.ones((4, 2))
print("A ones array is \n", ones_arr, " with dimensions ", ones_arr.shape[0], "\n")

A ones array is 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]  with dimensions  4 



In [9]:
ones_array = np.ones((4,3))
print("ones_array",ones_array,"\n Number of rows",ones_array.shape[0],"\n dimension of our array",ones_array.shape)

ones_array [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 Number of rows 4 
 dimension of our array (4, 3)


In [10]:
# return a new array of given shape and type, filled with fill_value
tens_arr = np.full((2,2), 10)
print("A filled array is \n", tens_arr, " with dimensions ", tens_arr.shape, "\n")

A filled array is 
 [[10 10]
 [10 10]]  with dimensions  (2, 2) 



In [11]:
twentys_array = np.full((4,4),10)
print("array filled with 20's\n= ",twentys_array)

array filled with 20's
=  [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [12]:
# return an array of zeros with the same shape and type as a given array
zeros_like_arr = np.zeros_like(ones_arr)
print("A zero like array is \n", zeros_like_arr, " with dimensions ", zeros_like_arr.shape, "\n")

A zero like array is 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]  with dimensions  (4, 2) 



In [13]:
zeros_like_array = np.zeros_like(twentys_array)
print("same shape and type as twentys array\n=",zeros_like_array)

same shape and type as twentys array
= [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [14]:
# return an array of ones with the same shape and type as a given array
ones_like_arr = np.ones_like(twentys_array)
print("A ones like array is \n", ones_like_arr, " with dimensions ", ones_like_arr.shape, "\n")

A ones like array is 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]  with dimensions  (4, 4) 



In [15]:
# Return a full array with the same shape and type as a given array.
full_like_arr = np.full_like(zeros_arr, 0.1, dtype=np.double)
print("A full like array is \n", full_like_arr, " with dimensions ", full_like_arr.shape, "\n")

A full like array is 
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]  with dimensions  (2, 3) 



## b. Create an array from existing data

In [25]:
# initialize an array with the given list
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("An array from given list is \n", arr_from_list, " with dimensions ", arr_from_list.shape, "\n")

An array from given list is 
 [1 2 3 4]  with dimensions  (4,) 



In [26]:
# # initialize an array by loading data from a txt file
# # txt_arr = np.loadtxt(path_to_txt_file)

# # initialize an array by loading data from a npy file
# loaded_arr = np.load(path_to_npy_file)

NameError: ignored

In [28]:
# loaded_arr = np.load(path_to_npy_file)

## c. Numerical ranges

In [31]:
# return evenly spaced values within a given interval
range_arr = np.arange(10)
print("An array given range is \n", range_arr, " with dimensions ", range_arr.shape, "\n")

# return evenly spaced numbers over a specified interval
linspace_arr = np.linspace(2.0, 3.0, num=5, endpoint=False)
print("An evenly spaced array given range is \n", linspace_arr, " with dimensions ", linspace_arr.shape, "\n")

An array given range is 
 [0 1 2 3 4 5 6 7 8 9]  with dimensions  (10,) 

An evenly spaced array given range is 
 [2.  2.2 2.4 2.6 2.8]  with dimensions  (5,) 



In [37]:
range_array = np.arange(8)
print(range_array,"the shape of the array is",range_array.shape)
linspace_array = np.linspace(2,4,9,endpoint = True)
print("the evenly distributed array",linspace_array, "the shape is",linspace_array.shape)

[0 1 2 3 4 5 6 7] the shape of the array is (8,)
the evenly distributed array [2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.  ] the shape is (9,)


## d. Create an array with random values

In [ ]:
a = np.random.randint(0, 10, size = (1,4))
print("Random integer array", a, "of shape ", a.shape)

In [39]:
ar = np.random.randint(0,20,size=(4,4))
ar

array([[16, 12,  1,  0],
       [ 7, 12,  2,  3],
       [17,  9,  3,  5],
       [ 9,  5, 12,  2]])

In [44]:
np.random.seed(0)
a = np.random.randint(0, 10, size = (1,4))
print("Random integer array with seed", a, "of shape ", a.shape)

Random integer array with seed [[5 0 3 3]] of shape  (1, 4)


In [46]:
# array of given shape and uniform distribution over [0,1)
uniform_random_array = np.random.rand(4,3)
uniform_random_array

array([[0.64817187, 0.36824154, 0.95715516],
       [0.14035078, 0.87008726, 0.47360805],
       [0.80091075, 0.52047748, 0.67887953],
       [0.72063265, 0.58201979, 0.53737323]])

In [48]:
# create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
uniform_rand_arr = np.random.rand(3,2)
print("A random array from a uniform distribution is \n", uniform_rand_arr, " with dimensions ", uniform_rand_arr.shape, "\n")

# return random integers from low (inclusive) to high (exclusive).
range_rand_int_arr = np.random.randint(5, size=(2, 4))
print("A random integer array from a range is \n", range_rand_int_arr, " with dimensions ", range_rand_int_arr.shape, "\n")

# For random samples from N(\mu, \sigma^2), use:
# sigma * np.random.randn(...) + mu
mu = 3
sigma =0.5
sample_normal_arr = mu + sigma * np.random.randn(2, 4)
print("A random array from a gaussian distribution is \n", sample_normal_arr)
print("with mu: ", mu)
print("with sigma: ", sigma)
print("with dimensions ", sample_normal_arr.shape)

A random array from a uniform distribution is 
 [[0.32504723 0.03842543]
 [0.63427406 0.95894927]
 [0.65279032 0.63505887]]  with dimensions  (3, 2) 

A random integer array from a range is 
 [[4 4 4 0]
 [4 3 2 0]]  with dimensions  (2, 4) 

A random array from a gaussian distribution is 
 [[2.84631759 2.81673803 3.55985598 2.77103879]
 [3.2126967  2.98601441 3.73799492 3.32339005]]
with mu:  3
with sigma:  0.5
with dimensions  (2, 4)


In [49]:
d = np.random.randn(2, 4)
d

array([[-0.36433431, -0.67877739, -0.35362786, -0.74074747],
       [-0.67502183, -0.13278426,  0.61980106,  1.79116846]])

# 3. Accessing and modifying data

## a. Indexing: Accessing values from Numpy Arrays

In [68]:
n = np.random.rand(4, 5, 6) # see this as 4 batches, each containing 5 rows and 6 columns
n

array([[[0.21876935, 0.75249617, 0.10687958, 0.74460324, 0.46978529,
         0.59825567],
        [0.14762019, 0.18403482, 0.64507213, 0.04862801, 0.24861251,
         0.54240852],
        [0.22677334, 0.38141153, 0.92223279, 0.92535687, 0.56674992,
         0.53347088],
        [0.01486002, 0.97789926, 0.5730289 , 0.791757  , 0.56155736,
         0.87733524],
        [0.58419583, 0.70884983, 0.14853345, 0.42845074, 0.69389007,
         0.10461974]],

       [[0.43960524, 0.16620215, 0.50697863, 0.81903586, 0.09010673,
         0.80006875],
        [0.56512635, 0.58934771, 0.19810066, 0.43611826, 0.29590376,
         0.03755768],
        [0.03068484, 0.453105  , 0.74486408, 0.55729541, 0.3851136 ,
         0.1680728 ],
        [0.83826132, 0.5990518 , 0.78271482, 0.84850918, 0.60316298,
         0.78106062],
        [0.61573688, 0.02116519, 0.75046461, 0.17604213, 0.45851421,
         0.51312271]],

       [[0.48402089, 0.84438579, 0.17481389, 0.01463488, 0.84876407,
         0.742674

In [53]:
ar = np.random.rand(2, 3, 4)
ar

array([[[0.34851937, 0.81496648, 0.98549143, 0.9689717 ],
        [0.90494835, 0.29655627, 0.99201124, 0.24942004],
        [0.10590615, 0.95095261, 0.23342026, 0.68976827]],

       [[0.05835636, 0.7307091 , 0.88172021, 0.2724369 ],
        [0.3790569 , 0.37429618, 0.74878826, 0.23780724],
        [0.1718531 , 0.44929165, 0.30446841, 0.83918912]]])

In [55]:
ar[0,0,0] + ar[1,0,-1]

0.6209562649585257

In [56]:
ar[1,0,-1]

0.2724368954659625

In [58]:
n[1, 2, 3] # returns the element located in the forth column of third row of the second batch.

0.2326269928297655

In [61]:
a = np.random.seed(10)


## b. Slicing: Accessing subsections of Numpy Arrays based on Indices

In [62]:
# slice along a batch
print(n[0, :, :]) # same as: n[0]

[[0.990345   0.4090541  0.16295443 0.63876176]
 [0.49030535 0.98940978 0.06530421 0.78323444]
 [0.2883985  0.24141862 0.66250457 0.24606318]]


In [63]:
print(n[0, 0:3, 0:4])

[[0.990345   0.4090541  0.16295443 0.63876176]
 [0.49030535 0.98940978 0.06530421 0.78323444]
 [0.2883985  0.24141862 0.66250457 0.24606318]]


In [66]:
# slice along multiple batches
print(n[:, 3, 4]) # returns the elements in the 4th row and 5th column across all batches

[0.37334076 0.82110566 0.59783665 0.67346693]


### Slicing at Interval

In [ ]:
#syntax for slicing at interval is start:stop:step_size 

In [67]:
print(n[0::2]) # slices from index 0 to the end of the dimension at intervals of 2

[[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665]
  [0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335]
  [0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607]
  [0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362]
  [0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]]

 [[0.59737165 0.90283176 0.53455795 0.59020136 0.03928177 0.35718176]
  [0.07961309 0.30545992 0.33071931 0.7738303  0.03995921 0.42949218]
  [0.31492687 0.63649114 0.34634715 0.04309736 0.87991517 0.76324059]
  [0.87809664 0.41750914 0.60557756 0.51346663 0.59783665 0.26221566]
  [0.30087131 0.02539978 0.30306256 0.24207588 0.55757819 0.56550702]]]


In [69]:
print(n[0::2, 1:4, 1::2]) # rows (2-5) and columns at an interval of 2, starting from 1

[[[0.18403482 0.04862801 0.54240852]
  [0.38141153 0.92535687 0.53347088]
  [0.97789926 0.791757   0.87733524]]

 [[0.41689841 0.33867913 0.71583087]
  [0.20595026 0.29383156 0.80356835]
  [0.09344038 0.78486672 0.86447919]]]


## c. Modifying Numpy Arrays

In [70]:
n_copy = np.copy(n)

In [76]:
# check if values in the two arrays are the same before copy, it is a boolean operation.
print(n_copy[2, 4, 1] == n[2, 4, 1])

n_copy[2, 4, 1] = 0.005

# check if values in the two arrays are the same after copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

False
False


### Modify single values

In [77]:
# check if values in the two arrays are the same before copy, it is a boolean operation.
print(n_copy[2, 4, 1] == n[2, 4, 1])

n_copy[2, 4, 1] = 0.005

# check if values in the two arrays are the same after copy
print(n_copy[2, 4, 1] == n[2, 4, 1])

False
False


In [78]:
print(n_copy[2, 4, 1])

0.005


### Modifying multiple values

In [80]:
# check if values in the two arrays are the same before copy
print(f"Are the arrays the same before modification: {n_copy[2, 3] == n[2, 3]}")
print(f"Before modifying values: {n_copy[2, 3]}")

n_copy[2, 3] = 0.5

print(f"After modifying values: {n_copy[2, 3]}")

# check if values in the two arrays are the same after copy
print(f"Are the arrays the same after modification: {n_copy[2, 3] == n[2, 3]}")

Are the arrays the same before modification: [False False False False False False]
Before modifying values: [0.5 0.5 0.5 0.5 0.5 0.5]
After modifying values: [0.5 0.5 0.5 0.5 0.5 0.5]
Are the arrays the same after modification: [False False False False False False]


# 4.Pivoting data

## a. Reshaping Arrays
Array reshaping is an operation that changes the shape of an arrays whilst maintaining the same data in the array. 

For instance, reshaping from (3, 4, 5) -> (2, 5, 6) or from (3, 4, 5) -> (6, 10). A reshape operation is valid, so long as the product of the new shape specified matched the product of the old shape.

#### Reshaping within the same number of dimensions

In [92]:
s = np.random.rand(3, 4, 5)
print(f"Original Shape: {s.shape}")

Original Shape: (3, 4, 5)


In [106]:
a = np.random.rand(4,3,3)
d = a.reshape(3,4,3)
d


array([[[0.08046362, 0.59427557, 0.28092147],
        [0.74244759, 0.2988272 , 0.75753668],
        [0.22636014, 0.00440764, 0.13978028],
        [0.2957637 , 0.19559382, 0.54888204]],

       [[0.20999217, 0.77849217, 0.4846799 ],
        [0.63934039, 0.16769631, 0.9246826 ],
        [0.71733995, 0.15481361, 0.72363361],
        [0.18640993, 0.82966457, 0.19664176]],

       [[0.96130067, 0.54759758, 0.2228636 ],
        [0.21272669, 0.62798796, 0.63327613],
        [0.30327904, 0.81636775, 0.41905672],
        [0.81385829, 0.26521517, 0.98342547]]])

In [100]:
a.shape

(4, 3, 3)

In [101]:
print(s)

[[[0.41330466 0.53546872 0.34264313 0.12957678 0.66282175]
  [0.93567    0.61272918 0.8427385  0.21790844 0.90317174]
  [0.00976998 0.22581273 0.13205513 0.90754295 0.91023064]
  [0.58105791 0.08749305 0.11687944 0.77107126 0.73279527]]

 [[0.08712836 0.3574632  0.77321162 0.1314716  0.53783243]
  [0.75472357 0.27252618 0.566517   0.47668497 0.55662069]
  [0.44073706 0.69373736 0.71823718 0.75638236 0.03732201]
  [0.6788354  0.4772208  0.10017139 0.61419623 0.83791451]]

 [[0.73389404 0.32156558 0.06785531 0.03733024 0.5591253 ]
  [0.1608527  0.26788819 0.23571196 0.01934746 0.15168642]
  [0.03390251 0.98183486 0.36048531 0.82546453 0.41223741]
  [0.25317915 0.23671088 0.7731156  0.67125691 0.70633089]]]


In [109]:
s1 = s.reshape(2, 6, 5)
print(f"Reshaped from s: {s1.shape}")

Reshaped from s: (2, 6, 5)


In [ ]:
print(s1)

### Reshaping to a different number of dimensions

In [126]:
r = np.arange(0,1200,6)

In [127]:
print(f"Original shape: {r.shape}")


Original shape: (200,)


In [128]:
print(r)

[   0    6   12   18   24   30   36   42   48   54   60   66   72   78
   84   90   96  102  108  114  120  126  132  138  144  150  156  162
  168  174  180  186  192  198  204  210  216  222  228  234  240  246
  252  258  264  270  276  282  288  294  300  306  312  318  324  330
  336  342  348  354  360  366  372  378  384  390  396  402  408  414
  420  426  432  438  444  450  456  462  468  474  480  486  492  498
  504  510  516  522  528  534  540  546  552  558  564  570  576  582
  588  594  600  606  612  618  624  630  636  642  648  654  660  666
  672  678  684  690  696  702  708  714  720  726  732  738  744  750
  756  762  768  774  780  786  792  798  804  810  816  822  828  834
  840  846  852  858  864  870  876  882  888  894  900  906  912  918
  924  930  936  942  948  954  960  966  972  978  984  990  996 1002
 1008 1014 1020 1026 1032 1038 1044 1050 1056 1062 1068 1074 1080 1086
 1092 1098 1104 1110 1116 1122 1128 1134 1140 1146 1152 1158 1164 1170
 1176 

In [129]:
# (120,) -> (3, 4, 10)
r1 = r.reshape(5, 4, 10) # this can also be written as r.reshape((3, 4, 10))
print(f"Reshaped from r: {r1.shape}")

Reshaped from r: (5, 4, 10)


In [130]:
print(r1)

[[[   0    6   12   18   24   30   36   42   48   54]
  [  60   66   72   78   84   90   96  102  108  114]
  [ 120  126  132  138  144  150  156  162  168  174]
  [ 180  186  192  198  204  210  216  222  228  234]]

 [[ 240  246  252  258  264  270  276  282  288  294]
  [ 300  306  312  318  324  330  336  342  348  354]
  [ 360  366  372  378  384  390  396  402  408  414]
  [ 420  426  432  438  444  450  456  462  468  474]]

 [[ 480  486  492  498  504  510  516  522  528  534]
  [ 540  546  552  558  564  570  576  582  588  594]
  [ 600  606  612  618  624  630  636  642  648  654]
  [ 660  666  672  678  684  690  696  702  708  714]]

 [[ 720  726  732  738  744  750  756  762  768  774]
  [ 780  786  792  798  804  810  816  822  828  834]
  [ 840  846  852  858  864  870  876  882  888  894]
  [ 900  906  912  918  924  930  936  942  948  954]]

 [[ 960  966  972  978  984  990  996 1002 1008 1014]
  [1020 1026 1032 1038 1044 1050 1056 1062 1068 1074]
  [1080 1086 1092 10

In [132]:
# (3, 4, 10) -> (6, 20)
r2 = r1.reshape(10, 20)
print(f"Reshaped from r1: {r2.shape}")

Reshaped from r1: (10, 20)


In [133]:
print(r2)

[[   0    6   12   18   24   30   36   42   48   54   60   66   72   78
    84   90   96  102  108  114]
 [ 120  126  132  138  144  150  156  162  168  174  180  186  192  198
   204  210  216  222  228  234]
 [ 240  246  252  258  264  270  276  282  288  294  300  306  312  318
   324  330  336  342  348  354]
 [ 360  366  372  378  384  390  396  402  408  414  420  426  432  438
   444  450  456  462  468  474]
 [ 480  486  492  498  504  510  516  522  528  534  540  546  552  558
   564  570  576  582  588  594]
 [ 600  606  612  618  624  630  636  642  648  654  660  666  672  678
   684  690  696  702  708  714]
 [ 720  726  732  738  744  750  756  762  768  774  780  786  792  798
   804  810  816  822  828  834]
 [ 840  846  852  858  864  870  876  882  888  894  900  906  912  918
   924  930  936  942  948  954]
 [ 960  966  972  978  984  990  996 1002 1008 1014 1020 1026 1032 1038
  1044 1050 1056 1062 1068 1074]
 [1080 1086 1092 1098 1104 1110 1116 1122 1128 1134 114

## b. Transposing Arrays
The transpose operation reverses the order of an array. It switches the rows to columns and vice versa. In a multi-dimensional array, the transpose operation moves the data from one axis to another in the order specified in the transpose method.

In [134]:
x=np.arange(50).reshape((5,10))
print("Shape of the original array", x.shape)
print("Original array\n", x)

Shape of the original array (5, 10)
Original array
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [137]:
x1=np.transpose(x)
print("Shape of the transposed array", x1.shape)
print("Transposed array\n", x1)

Shape of the transposed array (10, 5)
Transposed array
 [[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


In [140]:
x2 = np.transpose(x1)
x2


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [141]:
x2.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49]])

In [143]:
w = np.arange(60).reshape((3, 4, 5))
w

print("Shape of the Original array", w.shape)
print("Original array\n", w)

Shape of the Original array (3, 4, 5)
Original array
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


#### Transpose without specifying axes

In [144]:
# Original Shape: 3,4,5

w1 = np.transpose(w)  # 0->2, 1->1, 2->0   (0,1,2)->(2,1,0)
print("Shape of the transposed array", w1.shape)
print("Transposed array\n", w1)

Shape of the transposed array (5, 4, 3)
Transposed array
 [[[ 0 20 40]
  [ 5 25 45]
  [10 30 50]
  [15 35 55]]

 [[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]]


#### Transpose along specified axes

In [145]:
w

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [146]:
# Original Shape: 3,4,5

w2 = np.transpose(w, axes=(0, 2, 1)) # 0, 1, 2
print("Shape of the transposed array", w2.shape)
print("Transposed array\n", w2)

Shape of the transposed array (3, 5, 4)
Transposed array
 [[[ 0  5 10 15]
  [ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]]

 [[20 25 30 35]
  [21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]]

 [[40 45 50 55]
  [41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]]]


In [ ]:
w

In [147]:
# Original Shape: 3,4,5

w3 = np.transpose(w, axes=(1, 2, 0))
print("Shape of the transposed array", w3.shape)
print("Transposed array\n", w3)

Shape of the transposed array (4, 5, 3)
Transposed array
 [[[ 0 20 40]
  [ 1 21 41]
  [ 2 22 42]
  [ 3 23 43]
  [ 4 24 44]]

 [[ 5 25 45]
  [ 6 26 46]
  [ 7 27 47]
  [ 8 28 48]
  [ 9 29 49]]

 [[10 30 50]
  [11 31 51]
  [12 32 52]
  [13 33 53]
  [14 34 54]]

 [[15 35 55]
  [16 36 56]
  [17 37 57]
  [18 38 58]
  [19 39 59]]]


## c. Flattening Arrays
The flatten operation in Numpy collapses arrays of multiple dimensions into one dimension.


Different orders can be specified when flattening Numpy Arrays. See examples below.

In [148]:
k = np.random.rand(5, 6)

In [149]:
k

array([[0.87230532, 0.44852459, 0.33538451, 0.02970605, 0.99093675,
        0.68094952],
       [0.18915819, 0.04504555, 0.01313955, 0.66181062, 0.10751234,
        0.30995764],
       [0.30794745, 0.11747223, 0.94693142, 0.97739055, 0.90447925,
        0.79618015],
       [0.06542942, 0.71703863, 0.45591043, 0.15148371, 0.6467202 ,
        0.02923457],
       [0.75352087, 0.88973295, 0.01038004, 0.32742784, 0.82849109,
        0.11259759]])

### Flattening Arrays along the row (default order)

In [150]:
k1 = k.flatten() # all rows are stacked on each other into a 1D array.
k1

array([0.87230532, 0.44852459, 0.33538451, 0.02970605, 0.99093675,
       0.68094952, 0.18915819, 0.04504555, 0.01313955, 0.66181062,
       0.10751234, 0.30995764, 0.30794745, 0.11747223, 0.94693142,
       0.97739055, 0.90447925, 0.79618015, 0.06542942, 0.71703863,
       0.45591043, 0.15148371, 0.6467202 , 0.02923457, 0.75352087,
       0.88973295, 0.01038004, 0.32742784, 0.82849109, 0.11259759])

In [151]:
k1.shape

(30,)

### Flattening Arrays along the column

In [154]:
k2= k.flatten('F') # forms a 1D array where elements in a column are listed before moving to the next column.
k2

array([0.87230532, 0.18915819, 0.30794745, 0.06542942, 0.75352087,
       0.44852459, 0.04504555, 0.11747223, 0.71703863, 0.88973295,
       0.33538451, 0.01313955, 0.94693142, 0.45591043, 0.01038004,
       0.02970605, 0.66181062, 0.97739055, 0.15148371, 0.32742784,
       0.99093675, 0.10751234, 0.90447925, 0.6467202 , 0.82849109,
       0.68094952, 0.30995764, 0.79618015, 0.02923457, 0.11259759])

### Flattening Arrays using Ravel

In [155]:
k3 = k.ravel()
k3

array([0.87230532, 0.44852459, 0.33538451, 0.02970605, 0.99093675,
       0.68094952, 0.18915819, 0.04504555, 0.01313955, 0.66181062,
       0.10751234, 0.30995764, 0.30794745, 0.11747223, 0.94693142,
       0.97739055, 0.90447925, 0.79618015, 0.06542942, 0.71703863,
       0.45591043, 0.15148371, 0.6467202 , 0.02923457, 0.75352087,
       0.88973295, 0.01038004, 0.32742784, 0.82849109, 0.11259759])

### Flattening Arrays using Numpy Reshape


In [156]:
k4= k.reshape(-1)
k4

array([0.87230532, 0.44852459, 0.33538451, 0.02970605, 0.99093675,
       0.68094952, 0.18915819, 0.04504555, 0.01313955, 0.66181062,
       0.10751234, 0.30995764, 0.30794745, 0.11747223, 0.94693142,
       0.97739055, 0.90447925, 0.79618015, 0.06542942, 0.71703863,
       0.45591043, 0.15148371, 0.6467202 , 0.02923457, 0.75352087,
       0.88973295, 0.01038004, 0.32742784, 0.82849109, 0.11259759])

### Flatten vs Ravel
Bothe functions take in the same kind of arguments and order to flatten can be specified in both arrays. The difference lies in how the result 1D arrays are are created in both cases.

In [157]:
test = np.random.rand(4, 5)

In [158]:
test_flatten = test.flatten()
test_ravel = test.ravel()

print(f"test_flatten: {test_flatten}")
print(f"test_ravel: {test_ravel}")

test_flatten: [0.02469574 0.81435353 0.24890527 0.2491966  0.1582368  0.27605595
 0.42871035 0.25842181 0.36694704 0.34929559 0.33303578 0.3033672
 0.31512729 0.27022518 0.90029462 0.9669742  0.89669855 0.37327538
 0.64827922 0.31144182]
test_ravel: [0.02469574 0.81435353 0.24890527 0.2491966  0.1582368  0.27605595
 0.42871035 0.25842181 0.36694704 0.34929559 0.33303578 0.3033672
 0.31512729 0.27022518 0.90029462 0.9669742  0.89669855 0.37327538
 0.64827922 0.31144182]


In [159]:
test_flatten[0] = 5
print(f"Modified test_flatten: {test_flatten}")
print(f"Original Array: {test}")

Modified test_flatten: [5.         0.81435353 0.24890527 0.2491966  0.1582368  0.27605595
 0.42871035 0.25842181 0.36694704 0.34929559 0.33303578 0.3033672
 0.31512729 0.27022518 0.90029462 0.9669742  0.89669855 0.37327538
 0.64827922 0.31144182]
Original Array: [[0.02469574 0.81435353 0.24890527 0.2491966  0.1582368 ]
 [0.27605595 0.42871035 0.25842181 0.36694704 0.34929559]
 [0.33303578 0.3033672  0.31512729 0.27022518 0.90029462]
 [0.9669742  0.89669855 0.37327538 0.64827922 0.31144182]]


In [160]:
test_ravel[0] = 5
print(f"Modified test_ravel: {test_ravel}")
print(f"Original Array: {test}")

Modified test_ravel: [5.         0.81435353 0.24890527 0.2491966  0.1582368  0.27605595
 0.42871035 0.25842181 0.36694704 0.34929559 0.33303578 0.3033672
 0.31512729 0.27022518 0.90029462 0.9669742  0.89669855 0.37327538
 0.64827922 0.31144182]
Original Array: [[5.         0.81435353 0.24890527 0.2491966  0.1582368 ]
 [0.27605595 0.42871035 0.25842181 0.36694704 0.34929559]
 [0.33303578 0.3033672  0.31512729 0.27022518 0.90029462]
 [0.9669742  0.89669855 0.37327538 0.64827922 0.31144182]]


## d. Squeezing & Expanding Arrays

### Squeezing Numpy Arrays

The squeeze operation allows reduction of numpy arrays axes by dropping a specified axis, so long as it is of **unit length**. The product of the shape (overall size of the array) remains the same.

In [162]:
sq = np.random.rand(4, 1, 5)
print(f"Original Array: \n{sq}\n")
print(f"Shape of Original Array: {sq.shape}")

Original Array: 
[[[0.9011415  0.81358265 0.35906171 0.97570374 0.3859861 ]]

 [[0.01620939 0.01867446 0.54413954 0.44314632 0.02570015]]

 [[0.36830451 0.42032051 0.40540396 0.99807766 0.15667538]]

 [[0.43695891 0.27023265 0.96896344 0.58980904 0.70418642]]]

Shape of Original Array: (4, 1, 5)


In [163]:
# transforms from (4, 1, 5) -> (4, 5)
sq1 = np.squeeze(sq)
print(f"Squeezed Array: \n {sq1}\n")
print(f"Shape of Squeezed Array: {sq1.shape}")

Squeezed Array: 
 [[0.9011415  0.81358265 0.35906171 0.97570374 0.3859861 ]
 [0.01620939 0.01867446 0.54413954 0.44314632 0.02570015]
 [0.36830451 0.42032051 0.40540396 0.99807766 0.15667538]
 [0.43695891 0.27023265 0.96896344 0.58980904 0.70418642]]

Shape of Squeezed Array: (4, 5)


#### Squeezing Multiple Axes
Multiple unit length axes can be squeezed as shown below

In [164]:
q = np.random.rand(1, 4, 1, 5)
print(f"Original Array: \n {q}\n")
print(f"Shape of Original Array: {q.shape}")


Original Array: 
 [[[[0.64993667 0.75540708 0.88531427 0.25305273 0.22799381]]

  [[0.60264171 0.23616416 0.7309863  0.66399892 0.23927492]]

  [[0.18591473 0.31277572 0.36632897 0.58990679 0.75923894]]

  [[0.32235078 0.50202215 0.58383107 0.26660088 0.71384664]]]]

Shape of Original Array: (1, 4, 1, 5)


In [165]:
q1 = np.squeeze(q)
print(f"Multiple Squeezed Array: \n {q1}\n")
print(f"Shape of Multiple Squeezed Array: {q1.shape}")

Multiple Squeezed Array: 
 [[0.64993667 0.75540708 0.88531427 0.25305273 0.22799381]
 [0.60264171 0.23616416 0.7309863  0.66399892 0.23927492]
 [0.18591473 0.31277572 0.36632897 0.58990679 0.75923894]
 [0.32235078 0.50202215 0.58383107 0.26660088 0.71384664]]

Shape of Multiple Squeezed Array: (4, 5)


#### Squeezing specified axes

In [166]:
q2 = np.squeeze(q, axis=2)
print(f"Specified axis Squeezed Array: \n {q2}\n")
print(f"Shape of Specified axis Squeezed Array: {q2.shape}")

Specified axis Squeezed Array: 
 [[[0.64993667 0.75540708 0.88531427 0.25305273 0.22799381]
  [0.60264171 0.23616416 0.7309863  0.66399892 0.23927492]
  [0.18591473 0.31277572 0.36632897 0.58990679 0.75923894]
  [0.32235078 0.50202215 0.58383107 0.26660088 0.71384664]]]

Shape of Specified axis Squeezed Array: (1, 4, 5)


### Unsqueezing (Expanding) Numpy Arrays
This is the direct opposite of squeezing. A new unit axis is inserted in specified position. Multiple unit axes can be inserted by using a tuple on the axis attribute of the `expand_dims` method.

In [167]:
y = np.random.rand(4, 5)
print(f"Original Array: \n {y}\n")
print(f"Shape of Original Array: {y.shape}")

Original Array: 
 [[0.45727111 0.65023137 0.50266884 0.43139357 0.71776646]
 [0.01236084 0.08029438 0.57637295 0.81362172 0.56153623]
 [0.6035917  0.22058083 0.91954104 0.2055007  0.68833856]
 [0.37520982 0.21152903 0.82099134 0.11457444 0.77305069]]

Shape of Original Array: (4, 5)


In [168]:
# transforms from (4, 5) -> (4, 1, 5)
y1 = np.expand_dims(y, axis=1)
print(f"Expanded Array: \n {y1}\n")
print(f"Shape of Expanded Array: {y1.shape}")

Expanded Array: 
 [[[0.45727111 0.65023137 0.50266884 0.43139357 0.71776646]]

 [[0.01236084 0.08029438 0.57637295 0.81362172 0.56153623]]

 [[0.6035917  0.22058083 0.91954104 0.2055007  0.68833856]]

 [[0.37520982 0.21152903 0.82099134 0.11457444 0.77305069]]]

Shape of Expanded Array: (4, 1, 5)


In [169]:
# transforms from (4, 5) -> (1, 4, 1, 5)
y2 = np.expand_dims(y, axis=(0, 2))
print(f"Multi-axes Expanded Array: \n {y2}\n")
print(f"Shape of Multi-axes Expanded Array: {y2.shape}")

Multi-axes Expanded Array: 
 [[[[0.45727111 0.65023137 0.50266884 0.43139357 0.71776646]]

  [[0.01236084 0.08029438 0.57637295 0.81362172 0.56153623]]

  [[0.6035917  0.22058083 0.91954104 0.2055007  0.68833856]]

  [[0.37520982 0.21152903 0.82099134 0.11457444 0.77305069]]]]

Shape of Multi-axes Expanded Array: (1, 4, 1, 5)


# 5.Combining data

### 5a. Concatenation

A concatenation operation joins a sequence of arrays along an *existing* axis. All arrays must either have the same shape (except in the concatenating dimension) or be empty.

---



In [174]:
# Concatenating 2-d Arrays

array1 = np.array([[1, 2], [3, 4]])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([[5, 6]])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")


concatenated_array1 = np.concatenate((array1, array2), axis = 0) 
print("Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape, '\n')

# concatenated_array2 = np.concatenate((array1, array2), axis = 1) 
print("Concatenated array 2 along axis 0 (column-wise for 2-d arrays) is \n", concatenated_array1, "with dimensions ", concatenated_array1.shape)


Array 1 is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Array 2 is 
 [[5 6]]  with dimensions  (1, 2) 

Concatenated array 1 along axis 0 (row-wise for 2-d arrays) is 
 [[1 2]
 [3 4]
 [5 6]] with dimensions  (3, 2) 

Concatenated array 2 along axis 0 (column-wise for 2-d arrays) is 
 [[1 2]
 [3 4]
 [5 6]] with dimensions  (3, 2)


In [175]:
# Concatenating Numpy Arrays

array1 = np.random.randint(3, size = (3, 2, 2))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 2, 2))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

concatenated_array1 = np.concatenate((array1, array2), axis = 0) 
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

concatenated_array2 = np.concatenate((array1, array2), axis = 1) 
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

concatenated_array3 = np.concatenate((array1, array2), axis = 2) 
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)


Array 1 is 
 [[[0 2]
  [0 1]]

 [[1 1]
  [0 2]]

 [[1 0]
  [0 1]]]  with dimensions  (3, 2, 2) 

Array 2 is 
 [[[2 1]
  [3 0]]

 [[1 1]
  [2 0]]

 [[3 0]
  [2 0]]]  with dimensions  (3, 2, 2) 

Concatenated array 1 is 
 [[[0 2]
  [0 1]]

 [[1 1]
  [0 2]]

 [[1 0]
  [0 1]]

 [[2 1]
  [3 0]]

 [[1 1]
  [2 0]]

 [[3 0]
  [2 0]]] 

 and the dimensions of the concatenated array 1 are: 
 (6, 2, 2)
Concatenated array 2 is 
 [[[0 2]
  [0 1]
  [2 1]
  [3 0]]

 [[1 1]
  [0 2]
  [1 1]
  [2 0]]

 [[1 0]
  [0 1]
  [3 0]
  [2 0]]] 

 and the dimensions of the concatenated array 2 are: 
 (3, 4, 2)
Concatenated array 3 is 
 [[[0 2 2 1]
  [0 1 3 0]]

 [[1 1 1 1]
  [0 2 2 0]]

 [[1 0 3 0]
  [0 1 2 0]]] 

 and the dimensions of the concatenated array 3 are: 
 (3, 2, 4)


### 5b. Stacking

The stack operation joins a sequence of arrays along a *new* axis. The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension. All arrays need to be of the same size.  The stacked array has one more dimension than the input arrays.

In [177]:
# Stacking 1-d Arrays

array1 = np.array([1, 2, 3])
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.array([4, 5, 6])
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")


stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 is \n", stacked_array1, " with dimensions ", stacked_array1.shape)

stacked_array2 = np.stack((array1, array2), axis = 1) 
print("Stacked array 2 is \n", stacked_array2, " with dimensions ", stacked_array2.shape)

stacked_array3 = np.stack((array1, array2), axis = -1) 
print("Stacked array 3 is \n", stacked_array3, " with dimensions ", stacked_array3.shape)


Array 1 is 
 [1 2 3]  with dimensions  (3,) 

Array 2 is 
 [4 5 6]  with dimensions  (3,) 

Stacked array 1 is 
 [[1 2 3]
 [4 5 6]]  with dimensions  (2, 3)
Stacked array 2 is 
 [[1 4]
 [2 5]
 [3 6]]  with dimensions  (3, 2)
Stacked array 3 is 
 [[1 4]
 [2 5]
 [3 6]]  with dimensions  (3, 2)


In [179]:

# Stacking Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 has dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 has dimensions ", array2.shape, "\n")

stacked_array1 = np.stack((array1, array2), axis = 0)
print("Stacked array 1 has dimensions", stacked_array1.shape, "\n")

stacked_array2 = np.stack((array1, array2), axis = 1) 
print("Stacked array 2 has dimensions", stacked_array2.shape, "\n")

stacked_array3 = np.stack((array1, array2), axis = 2) 
print(stacked_array3)
print("Stacked array 3 has dimensions", stacked_array3.shape, "\n")

stacked_array4 = np.stack((array1, array2), axis = -1)
print("Stacked array 4 has dimensions", stacked_array4.shape, "\n")



Array 1 has dimensions  (3, 4, 5) 

Array 2 has dimensions  (3, 4, 5) 

Stacked array 1 has dimensions (2, 3, 4, 5) 

Stacked array 2 has dimensions (3, 2, 4, 5) 

[[[[0 1 0 0 1]
   [0 0 3 1 2]]

  [[1 2 2 0 1]
   [1 3 1 3 1]]

  [[1 0 2 0 1]
   [1 1 3 1 1]]

  [[0 0 2 0 0]
   [2 1 2 1 1]]]


 [[[1 2 1 2 0]
   [3 1 1 2 0]]

  [[2 0 1 2 2]
   [3 2 2 3 2]]

  [[1 1 0 1 0]
   [2 0 1 3 0]]

  [[0 1 1 0 2]
   [1 3 3 1 1]]]


 [[[2 1 0 2 2]
   [1 1 2 1 3]]

  [[2 0 2 2 0]
   [1 0 2 2 1]]

  [[2 1 2 0 1]
   [2 3 0 1 2]]

  [[2 1 0 2 2]
   [1 3 1 3 3]]]]
Stacked array 3 has dimensions (3, 4, 2, 5) 

Stacked array 4 has dimensions (3, 4, 5, 2) 



###5c. Repeat

The repeat operation repeats elements of an array. The number of repetitions for each element is broadcasted to fit the shape of the given axis. The axis parameter specifies along which axis to repeat values. By default, it uses the flattened input array, and return a flat output array.

In [180]:

# Repeat in Numpy Arrays

original_array = np.array([[1,2],[3,4]])
print("Array is \n", original_array, " with dimensions ", original_array.shape, "\n")

repeated_array1 = np.repeat(original_array, 2)
print("Repeated array 1 is \n", repeated_array1, "\n\n", "and the dimensions of the repeated array 1 are: \n", repeated_array1.shape, "\n")

repeated_array2 = np.repeat(original_array, 3, axis=0)
print("Repeated array 2 is \n", repeated_array2, "\n\n", "and the dimensions of the repeated array 2 are: \n", repeated_array2.shape, "\n")

repeated_array3 = np.repeat(original_array, 3, axis=1)
print("Repeated array 3 is \n", repeated_array3, "\n\n", "and the dimensions of the repeated array 3 are: \n", repeated_array3.shape, "\n")

repeated_array4 = np.repeat(original_array, [2,3], axis=0)
print("Repeated array 4 is \n", repeated_array4, "\n\n", "and the dimensions of the repeated array 4 are: \n", repeated_array4.shape, "\n")


Array is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Repeated array 1 is 
 [1 1 2 2 3 3 4 4] 

 and the dimensions of the repeated array 1 are: 
 (8,) 

Repeated array 2 is 
 [[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

 and the dimensions of the repeated array 2 are: 
 (6, 2) 

Repeated array 3 is 
 [[1 1 1 2 2 2]
 [3 3 3 4 4 4]] 

 and the dimensions of the repeated array 3 are: 
 (2, 6) 

Repeated array 4 is 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

 and the dimensions of the repeated array 4 are: 
 (5, 2) 



# 6. Math operations

In this section we will cover some commonly used mathematical operations
1. Broadcasting
1. Point-wise/element-wise operations
1. Redution operations
1. Comparison operations
1. Vector/Matrix operations

## a. Broadcasting

In [182]:
# Broadcasting b/w arrays of different dimensions
# Note: When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the arrays should have length 1 in that specific dimension

row_arr = np.random.rand(1,3)
print("A row array: \n", row_arr, " with dimensions ", row_arr.shape, "\n")
col_arr = np.random.rand(4,1)
print("A column array: \n", col_arr, " with dimensions ", col_arr.shape, "\n")

add_arr = row_arr + col_arr
print("row array + column array = ")
print(add_arr," with dimensions ", add_arr.shape, "\n")
mul_arr = row_arr * col_arr
print("row array * column array = ")
print(mul_arr," with dimensions ", mul_arr.shape, "\n")


A row array: 
 [[0.88519079 0.89641751 0.80681856]]  with dimensions  (1, 3) 

A column array: 
 [[0.78703743]
 [0.81153715]
 [0.32456205]
 [0.62083596]]  with dimensions  (4, 1) 

row array + column array = 
[[1.67222821 1.68345494 1.59385598]
 [1.69672793 1.70795466 1.61835571]
 [1.20975283 1.22097956 1.13138061]
 [1.50602674 1.51725347 1.42765452]]  with dimensions  (4, 3) 

row array * column array = 
[[0.69667828 0.70551413 0.6349964 ]
 [0.71836521 0.72747611 0.65476323]
 [0.28729933 0.2909431  0.26186268]
 [0.54955827 0.55652823 0.50090197]]  with dimensions  (4, 3) 




## b.Element-wise operations

In [183]:
rand_arr_1 = np.random.rand(2,3)
print("A random array1 : \n", rand_arr_1, " with dimensions ", rand_arr_1.shape, "\n")
rand_arr_2 = np.random.rand(2,3)
print("A random array2 : \n", rand_arr_2, " with dimensions ", rand_arr_2.shape, "\n")
scalar = 5.0

# Addition with Scalars

new_arr_1 = rand_arr_1 + scalar
print("random array1 + 5.0 =")
print(new_arr_1, "\n")

# Multiplication with Scalars
new_arr_2 = rand_arr_1 * scalar
print("random array1 * 5.0 =")
print(new_arr_2, "\n")

# Elementwise Addition of Arrays
new_arr_3 = rand_arr_1 + rand_arr_2
print("random array1 + random array2 =")
print(new_arr_3, "\n")

# Elementwise Multiplication of Arrays aka Hadmard Product
new_arr_4 = rand_arr_1 * rand_arr_2
print("random array1 * random array2 =")
print(new_arr_4, "\n") # also equivalent to np.multiply(array1, array2)

# Absolute value
new_arr_5 = np.abs(-10*rand_arr_1)
print("abs (-10 * random array1) =")
print(new_arr_5, "\n")

# Square root value
new_arr_6 = np.sqrt(rand_arr_1)
print('sqrt(random array1) = \n', new_arr_6, "\n")

A random array1 : 
 [[0.18159119 0.85264606 0.95783722]
 [0.25259335 0.06943365 0.72945206]]  with dimensions  (2, 3) 

A random array2 : 
 [[0.91705518 0.84345826 0.01306861]
 [0.4308811  0.39540359 0.42141242]]  with dimensions  (2, 3) 

random array1 + 5.0 =
[[5.18159119 5.85264606 5.95783722]
 [5.25259335 5.06943365 5.72945206]] 

random array1 * 5.0 =
[[0.90795593 4.26323029 4.78918611]
 [1.26296675 0.34716825 3.64726028]] 

random array1 + random array2 =
[[1.09864637 1.69610432 0.97090584]
 [0.68347445 0.46483724 1.15086448]] 

random array1 * random array2 =
[[0.16652914 0.71917136 0.0125176 ]
 [0.1088377  0.02745431 0.30740016]] 

abs (-10 * random array1) =
[[1.81591186 8.52646059 9.57837222]
 [2.52593349 0.6943365  7.29452056]] 

sqrt(random array1) = 
 [[0.42613517 0.92338836 0.97869159]
 [0.50258666 0.26350266 0.85407965]] 



## c.Reduction

In [184]:
rand_arr = np.random.rand(2,3)
print('random array: \n', rand_arr, "\n")

max_val = np.max(rand_arr)
print('Maximum value of array \n', max_val, "\n")
min_val = np.min(rand_arr)
print('Minimum value of array \n', min_val, "\n")

sum_val = np.sum(rand_arr)
print('Sum of array \n', sum_val, "\n")
max_idx = np.argmax(rand_arr, axis=0)
print('Maximum value\'s index of array along axis 0 \n', max_idx, "\n")
min_idx = np.argmin(rand_arr, axis=1)
print('Minimum value\'s index of array along axis 1 \n', min_idx, "\n")

mean_val = np.mean(rand_arr)
print('Mean value of array \n', mean_val, "\n")
std_val = np.std(rand_arr)
print('Standard deviation value of array \n', std_val, "\n")
norm_val = np.linalg.norm(rand_arr)
print('Norm value of array \n', norm_val, "\n")

random array: 
 [[0.1402355  0.76123849 0.6924583 ]
 [0.61182749 0.92891012 0.71541838]] 

Maximum value of array 
 0.9289101150237433 

Minimum value of array 
 0.1402354961897605 

Sum of array 
 3.850088275806984 

Maximum value's index of array along axis 0 
 [1 1 1] 

Minimum value's index of array along axis 1 
 [0 0] 

Mean value of array 
 0.641681379301164 

Standard deviation value of array 
 0.24397708895024586 

Norm value of array 
 1.6815703597669895 



## d.Comparision

In [186]:
rand_arr_1 = np.random.rand(2,3)
print('random array1: \n', rand_arr_1, '\n')
rand_arr_2 = np.random.rand(2,3)
print('random array2: \n', rand_arr_2, '\n')

# Element-wise Comparison Operations
greater_compare = rand_arr_1 > rand_arr_2
print('random array1 > random array2')
print(greater_compare, '\n')

less_compare = rand_arr_1 < rand_arr_2
print('random array1 < random array2')
print(less_compare, '\n')

not_equal_compare = rand_arr_1 != rand_arr_2
print('random array1 != random array2')
print(not_equal_compare, '\n')

# Combining reduction operations with boolean arrays
print("any values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(), "\n")

print("all values for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).all(), "\n")

print("any values along first axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=0), "\n")

print("any values along second axis for random array1 > random array2:")
print((rand_arr_1 > rand_arr_2).any(axis=1), "\n")

print("any values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).any(), "\n")

print("all values for random array1 != random array2:")
print((rand_arr_1 != rand_arr_2).all(), "\n")

random array1: 
 [[0.64318656 0.49611844 0.65693785]
 [0.2930088  0.14126333 0.83674618]] 

random array2: 
 [[0.11316804 0.11198337 0.45891261]
 [0.4149644  0.94542654 0.41213633]] 

random array1 > random array2
[[ True  True  True]
 [False False  True]] 

random array1 < random array2
[[False False False]
 [ True  True False]] 

random array1 != random array2
[[ True  True  True]
 [ True  True  True]] 

any values for random array1 > random array2:
True 

all values for random array1 > random array2:
False 

any values along first axis for random array1 > random array2:
[ True  True  True] 

any values along second axis for random array1 > random array2:
[ True  True] 

any values for random array1 != random array2:
True 

all values for random array1 != random array2:
True 



## e.Vector/Matrix operations

In [187]:
# Vector x Vector
array1 = np.random.randn(3)
array2 = np.random.randn(3)

print('Array1 \n', array1, 'with dimension ', array1.shape, '\n')
print('Array2 \n', array2, 'with dimension ', array2.shape, '\n')

matmul_arr = np.matmul(array1, array2)
another_arr = array1@array2
print('Matmul of the two arrays can be derived by using np.matmul(array1, array2) \n', matmul_arr)
print("Matmul of the two arrays can also be derived by using array1@array2 \n", another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Vector
array3 = np.random.randn(3, 4)
array4 = np.random.randn(4)

print('Array3 \n', array3, 'with dimension ', array3.shape, '\n')
print('Array4 \n', array4, 'with dimension ', array4.shape, '\n')

matmul_arr = np.matmul(array3, array4)
another_arr = array3@array4
print('Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) \n', matmul_arr)
print('Matmul of a vector and a matrix can also be derived by using array3@array4 \n', another_arr)
print('Dimensions of resulting product: \n', matmul_arr.shape)

# Matrix x Matrix 

matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

print('Matrix1 \n', matrix1, 'with dimension ', matrix1.shape, '\n')
print('Matrix2 \n', matrix2, 'with dimension ', matrix2.shape, '\n')

matmul_mat = np.matmul(matrix1, matrix2)
print('Matmul of two matrices can be derived by using np.matmul(matrix1, matrix2) \n', matmul_mat)
print('Dimensions of resulting product: \n', matmul_mat.shape, "\n")

Array1 
 [-1.19376926 -1.16472182  0.83583178] with dimension  (3,) 

Array2 
 [-0.87731628  0.06730311 -0.21366744] with dimension  (3,) 

Matmul of the two arrays can be derived by using np.matmul(array1, array2) 
 0.7903337780545778
Matmul of the two arrays can also be derived by using array1@array2 
 0.7903337780545778
Dimensions of resulting product: 
 ()
Array3 
 [[ 0.18352954 -0.28802781  0.67252175 -1.06059989]
 [ 0.76610474 -0.04469236 -0.0673834  -1.2281184 ]
 [-0.21345513 -0.58338066 -1.17613076  0.93616502]] with dimension  (3, 4) 

Array4 
 [-0.33002594 -0.14039343  0.79584245 -0.4422713 ] with dimension  (4,) 

Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) 
 [ 0.98416196  0.24297502 -1.19770517]
Matmul of a vector and a matrix can also be derived by using array3@array4 
 [ 0.98416196  0.24297502 -1.19770517]
Dimensions of resulting product: 
 (3,)
Matrix1 
 [[0 3 0]
 [1 0 2]] with dimension  (2, 3) 

Matrix2 
 [[3 2]
 [2 3]
 [0 0]] with

In [188]:
rand_mat_1 = np.random.rand(4,2)
rand_mat_2 = np.random.rand(2,3)
print('Matrix1 \n', rand_mat_1, 'with dimension ', rand_mat_1.shape, '\n')
print('Matrix2 \n', rand_mat_2, 'with dimension ', rand_mat_2.shape, '\n')

# dot product
dot_mat = np.dot(rand_mat_1, rand_mat_2)
another_mat = rand_mat_1@rand_mat_2
print('Dot product of two matrices can be derived by using np.dot(mat1, mat2) \n', dot_mat)
print('Dot product of two matrices can also be derived by using mat1@mat2 \n', another_mat)
print('Dimensions of resulting product: \n', dot_mat.shape)

a = np.ones([9, 5, 7, 4])
b = np.ones([9, 5, 4, 3])
print('array1 \'s dimension ', a.shape, '\n')
print('array2 \'s dimension ', b.shape, '\n')

# matmul with multi-dimenstion arrays
c = np.matmul(a,b)
print('Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) \n')
print('Dimensions of resulting product: \n', c.shape)

Matrix1 
 [[0.17284379 0.02700308]
 [0.22909131 0.40195862]
 [0.51558873 0.21015325]
 [0.16511258 0.68994799]] with dimension  (4, 2) 

Matrix2 
 [[0.09518928 0.34832992 0.80896286]
 [0.45963719 0.6261243  0.20364683]] with dimension  (2, 3) 

Dot product of two matrices can be derived by using np.dot(mat1, mat2) 
 [[0.0288645  0.07711395 0.1453233 ]
 [0.20656217 0.33147542 0.26718396]
 [0.14567277 0.31117704 0.45988918]
 [0.3328427  0.48950685 0.27407566]]
Dot product of two matrices can also be derived by using mat1@mat2 
 [[0.0288645  0.07711395 0.1453233 ]
 [0.20656217 0.33147542 0.26718396]
 [0.14567277 0.31117704 0.45988918]
 [0.3328427  0.48950685 0.27407566]]
Dimensions of resulting product: 
 (4, 3)
array1 's dimension  (9, 5, 7, 4) 

array2 's dimension  (9, 5, 4, 3) 

Matmul of two multi-dimension arrays can be derived by using np.matmul(array1, array2) 

Dimensions of resulting product: 
 (9, 5, 7, 3)


###Tensordot

Understanding tensordot function will help you in writing succint code for your homeworks especially in Convolutional Neural Net assignment.

To give a brief overview: 
We input the arrays and the respective axes along which the sum-reductions are intended. The axes that take part in sum-reduction are removed in the output and all of the remaining axes from the input arrays are spread-out as different axes in the output keeping the order in which the input arrays are fed.

To understand in depth please checkout: https://stackoverflow.com/questions/41870228/understanding-tensordot

In [189]:
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
print('A \'s dimension ', a.shape, '\n')
print('B \'s dimension ', b.shape, '\n')

# compute tensor dot product along specified axes.
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print("A⨂B =\n", c, ' with dimension', c.shape, '\n')

# this equals to 
d = np.zeros((5,2))
for i in range(5):
  for j in range(2):
    for k in range(3):
      for n in range(4):
        d[i,j] += a[k,n,i] * b[n,k,j]
print("tensor dot is equal to sum over certain dimensions.\n")
print(c==d)

A 's dimension  (3, 4, 5) 

B 's dimension  (4, 3, 2) 

A⨂B =
 [[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]  with dimension (5, 2) 

tensor dot is equal to sum over certain dimensions.

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
