<a href="https://colab.research.google.com/github/Lotfullah21/PyLibraries/blob/main/Linear_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import math

In [16]:
def L(x,y,w):
  delta = 1
  scores = w.dot(x)
  correct_class_score  = scores[y]
  D = w.shape[0]
  loss_i = 0
  for j in range(D):
    if j==y:
      continue
    loss_i = loss_i + max(0,scores[j]-correct_class_score+delta)

  return loss_i



In [12]:
def Loss_vectorized(x,y,w):
  delta = 1.0
  scores = w.dot(x)
  margins = np.maximum(0,scores[y]+delta)
  margins[y] = 0
  loss_i = np.sum(margins)
  return loss_i

  

In [13]:
a = np.array([2,1,3])
print(a)
p = np.exp(a)/np.sum(np.exp(a)) # just by doing this,there might be numeric problem, potential blow up
print("np.exp(a) = ", np.exp(a))
print("np.sum(a) = ",np.sum(a))
print("softmax = ",p)
print("Highest probability = ",np.max(p))

[2 1 3]
np.exp(a) =  [ 7.3890561   2.71828183 20.08553692]
np.sum(a) =  6
softmax =  [0.24472847 0.09003057 0.66524096]
Highest probability =  0.6652409557748219


In [14]:
a = np.array([2,1,3])
a = a - np.max(a) # first, we shift the value of a, so that the highest number would be 0.
print(a)
s = np.exp(a)/np.sum(np.exp(a))
p = np.exp(a)/np.sum(np.exp(a)) # just by doing this,there might be numeric problem, potential blow up
print("np.exp(a) = ", np.exp(a))
print("np.sum(a) = ",np.sum(a))
print("softmax = ",s)
print("Highest probability = ",np.max(s))

[-1 -2  0]
np.exp(a) =  [0.36787944 0.13533528 1.        ]
np.sum(a) =  -3
softmax =  [0.24472847 0.09003057 0.66524096]
Highest probability =  0.6652409557748218


array([0.36787944, 0.13533528, 1.        ])

In [ ]:


bestloss = float("inf")
for num in range(1000):
  W = np.random.rand(10,3073)*0.001
  loss = L(x,y,W)e
  if loss < bestloss:
    bestloss = loss
    bestw = W

## Optimization 
optimization is the process of finding the set of parameters **W** that minimizes the loss function.

We ara going to examine different ways to find the optimal **W's**,Lets look at the first one which is a Random search.


In [17]:
# computing derivatives
x = -2 ; y = 5 ; z = -4
q = x+y
f = q*z

dfdz = q
dfdq = z
dqdx = 1
dqdy = 1
dfdx = dfdq*dqdx
dfdy = dfdq*dfdq


## Sigmoid
sigmoid derivative f = 1.0/(1+exp(-x))

df/dx = **(1-f)*f**

In [31]:
# Computing the derivative of sigmoid function
W = [2,-1,-3]
x = [-1,-2]
# forward pass

dot = W[0]*x[0] + W[1]*x[1] + W[2]
f = 1.0/(1+math.exp(-dot))

# backward pass
dfdot = (1-f)*f
dx = [W[0]*dfdot,W[1]*dfdot] # backprop into x
dw = [x[0]*dfdot, x[1]*dfdot, 1.0*dfdot]



In [33]:
print("dot",dot,"\n","f = ",f,"\n","dw = ",dw,"\n","dx = ",dx,"\n","dfdot",dfdot)

dot -3 
 f =  0.04742587317756678 
 dw =  [-0.04517665973091214, -0.09035331946182427, 0.04517665973091214] 
 dx =  [0.09035331946182427, -0.04517665973091214] 
 dfdot 0.04517665973091214


In [48]:
x = 221
y = -4
sigmoid = 1.0/(1+math.exp(-dot))
numerator = 1 + sigmoid
## take care of ^ and ** operation 
xd = (x+y)^2
denominator = sigmoid + xd
function = numerator/denominator
function 


0.004781731029261205

In [49]:
x = 221
y = -4
sigmoid = 1.0/(1+math.exp(-dot))
numerator = 1 + sigmoid 
xd = (x+y)**2
denominator = sigmoid + xd
function = numerator/denominator
function 


2.2243513734832026e-05

In [50]:
x = 221
y = -4
sigmoid = 1.0/(1+math.exp(-dot))
numerator = 1 + sigmoid 
xd = x+y
sqr = xd**2
denominator = sigmoid + sqr
invdeno = 1.0/denominator
function  = numerator * invdeno
function 

2.2243513734832026e-05

In [61]:
# Gradients for Vectorized operations
W = np.random.randn(5,10)
X = np.random.randn(10,4)
D = W.dot(X)

dD = np.random.randn(*D.shape)
dW = dD.dot(X.T)
dX = W.T.dot(dD)
D

array([[-3.22657249, -1.13827725,  2.77604789,  4.41567393],
       [ 0.59610765,  3.29974564, -0.39595864, -3.12754961],
       [ 3.51129092,  1.91107531, -4.32252441, -3.40586234],
       [ 0.39033825,  0.17158861,  3.00234262,  5.5839248 ],
       [-1.55964413, -2.38326322, -0.2223106 ,  3.14397342]])

In [58]:
dX

array([[ 0.21520217, -0.26935772,  0.24129473, -1.26036254],
       [ 0.35231097, -1.33181966,  0.41861895, -1.55978572],
       [ 1.58455215, -0.40694503, -0.50347949, -1.46217353],
       [ 0.4379125 , -0.35794722, -1.5427916 , -3.84812589],
       [ 2.7966239 ,  0.16002526, -0.06651985,  3.7917234 ],
       [-2.13590064, -1.05946645,  0.71752887, -3.47247034],
       [ 2.37603856, -1.16390018, -0.70456494, -4.45250507],
       [ 0.8503133 ,  1.01255521, -0.35899234,  0.69269619],
       [ 0.61042989, -1.03399797, -0.29349437, -2.36496947],
       [ 1.74995578, -0.49204388, -2.06145339, -4.31866831]])

In [59]:
dD

array([[-0.23443903,  1.15732879, -0.41067861,  0.86115351],
       [ 0.95994773, -0.20139285, -0.51810474,  0.17695371],
       [ 0.80780075, -0.25311062,  0.27735657,  0.47104445],
       [-0.24775676,  0.21515489,  0.50447289,  2.30451712],
       [-0.75052401,  0.03603219,  0.14004692,  0.77070782]])

In [60]:
dW

array([[ 1.80107042,  0.07230032,  0.46239339, -0.92630165,  1.53306864,
        -0.93123171, -0.84811929, -1.09530361,  2.17378268, -1.96693561],
       [-0.82762489, -0.08683719,  0.37076405,  0.11434574,  0.21854968,
         0.65887811, -1.86731138,  1.23338107,  0.54880673,  1.08466732],
       [-0.82556486,  0.23228975,  0.48566763, -0.62730777, -0.62489611,
        -0.27890227, -0.4328654 ,  2.09010385,  0.80712813,  0.06804107],
       [ 1.15690898,  3.09956862,  1.09708643, -0.04784575, -0.88053458,
        -2.29661354,  1.51517467,  2.42064985,  3.95198712, -2.34910596],
       [ 0.91222969,  1.66409353,  0.13736467,  0.78323691, -0.37804552,
        -0.86808414,  1.42615174, -0.01429933,  1.15101689, -0.9071718 ]])