<a href="https://colab.research.google.com/github/Lotfullah21/PyLibraries/blob/main/Linear_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
def L_i(x,y,w):
  delta = 1
  scores = w.dot(x)
  correct_class_score  = scores[y]
  D = w.shape[0]
  loss_i = 0
  for j in range(D):
    if j==y:
      continue
    loss_i = loss_i + max(0,scores[j]-correct_class_score+delta)

  return loss_i



In [8]:
x = np.array([2,3,1])
w = np.array([0.1,-1,0.2])
y = np.array([1])
L_i(x,y,w)

IndexError: ignored

In [5]:
def Loss_vectorized(x,y,w):
  delta = 1.0
  scores = w.dot(x)
  margins = np.maximum(0,scores[y]+delta)
  margins[y] = 0
  loss_i = np.sum(margins)
  return loss_i

  

In [6]:
x = np.array([2,3,1])
w = np.array([0.1,-1,0.2])
y = 1
Loss_vectorized(x,y,w)

IndexError: ignored

In [36]:
a = np.array([2,1,3])
print(a)
p = np.exp(a)/np.sum(np.exp(a)) # just by doing this,there might be numeric problem, potential blow up
print("np.exp(a) = ", np.exp(a))
print("np.sum(a) = ",np.sum(a))
print("softmax = ",p)
print("Highest probability = ",np.max(p))

[2 1 3]
np.exp(a) =  [ 7.3890561   2.71828183 20.08553692]
np.sum(a) =  6
softmax =  [0.24472847 0.09003057 0.66524096]
Highest probability =  0.6652409557748219


In [37]:
a = np.array([2,1,3])
a = a - np.max(a) # first, we shift the value of a, so that the highest number would be 0.
print(a)
s = np.exp(a)/np.sum(np.exp(a))
p = np.exp(a)/np.sum(np.exp(a)) # just by doing this,there might be numeric problem, potential blow up
print("np.exp(a) = ", np.exp(a))
print("np.sum(a) = ",np.sum(a))
print("softmax = ",s)
print("Highest probability = ",np.max(s))

[-1 -2  0]
np.exp(a) =  [0.36787944 0.13533528 1.        ]
np.sum(a) =  -3
softmax =  [0.24472847 0.09003057 0.66524096]
Highest probability =  0.6652409557748218


In [12]:
np.exp(a)

array([ 7.3890561 ,  2.71828183, 20.08553692])